---
- hosts: localhost
  vars:
    LICENSE_FILE: "/exports/bastion/setup/license/license_file.zip"
    CAS_SIZING_FILE: "/exports/bastion/setup/license/cas_size.txt"
  tasks:

  # Host definitions
    - import_role:
        name: common/read_sas_license_information
  
    - name: deleting old cas_size file
      file:
        state: absent
        path: "{{ CAS_SIZING_FILE }}"

    - name: build json prototype variable
      set_fact:
        JSON_RETURN:
          SAS_DRIVE: "{{ SAS_HOME_PATH }}"
          SAS_STUDIO: "{{ SAS_STUDIO_PATH }}"


    - name: writing json to file
      blockinfile:
        marker: "#DATA#"
        path: "{{ CAS_SIZING_FILE }}"
        block: >-
          {{ ('' ~ (JSON_RETURN) ).replace("{u'", "{'").replace(" u'", " '") }}
        create: yes

    - name: write viya-version out
      shell: |
        echo "{{ SAS_LICENSE.viya_version }}" > /tmp/viya_version.txt