---

- name: download SOE file
  get_url:
    url: "{{ DEPLOYMENT_DATA_LOCATION }}"
    dest: "{{ TEMPORARY_SOE_FILE }}"
    mode: '0660'
    owner: "{{ ansible_user_id }}"
  register: task_result
  until: task_result | success
  retries: 10
  delay: 5