---
# defaults file for getLocalVIRK

LOCAL_DIRECTORY_MIRROR: "/mnt/viyashare/mirror"

MIRROR_MANAGER_URL: "https://support.sas.com/installation/viya/34/sas-mirror-manager/lax/mirrormgr-linux.tgz"
ORCHESTRATION_MIRROR_MANAGER: "/tmp/mirrormgr"
ORCHESTRATION_DIRECTORY: "/tmp"
